### ISSUE TITLE
Handlers Diary RSS Full Feed Malformed Item Body

### ISSUE THREAD

**Issue by nbuuck** [jullrich/ISC-Bugs#21]
As seen at https://gist.github.com/nbuuck/2d2fc4ded75311a995dffacd68fcb294#file-rssfeed_full-xml-L16, paragraphs being returned in rssfeed_full.xml occasionally contain incomplete markup tags like `width:800px" />` near the end of the line,

**Comment by jrmain** [comment]
LOL. I've been begging SANS to fix the RSS feed for literally years, without result. Some of the posts are so messed up that they crash Firefox. SANS's most recent (rather lame) advice was to use the title-only feed (https://isc.sans.edu/rssfeed.xml), but even that no longer works, as it recently started including full posts instead of just titles. I'm torn between Twitter shaming SANS every day until it's fixed, and just giving up on SANS altogether. I've also toyed with the idea of creating a web site that mirrors the SANS content, but with an RSS feed that works. I've actually done the required work and it functions well, but I balked at the probable flack I'd get from SANS if I went public with it.

**Comment by jrmain** [comment]
At the suggestion of a SANS representative on Twitter, I switched to the title-only feed (isc.sans.edu/rssfeed.xml) so my feed reader doesn't have to deal with the messed up full feed (isc.sans.edu/rssfeed_full.xml). That worked for a while, but recently the title-only feed started showing full articles. So we're back to square one.

**Comment by jullrich** [comment]
fixed the "normal" feed to only show the first paragraph of the body and strip all HTML tags. The "full" feed continues to display the entire body, and as far as I can tell, "correct" in that the HTML content is inside an encoded block. But will review some of the standards to see if there is a better way to do this.

**Comment by jrmain** [comment]
Problems remain. Yesterday's post "Use of the Open Graph Protocol to Disguise Malicious Facebook Links" (https://isc.sans.edu/diary/rss/22684) has problems near the YouTube image. Content is missing from 'onload=' onward in the quoted block, and from 'smarturl.it' onward in the following paragraph. After 'smarturl.it' I'm seeing HTML markup: 'width:300px" />'. The image is missing. Happens in Firefox and Chrome, in both Feedly and The Old Reader. I'll continue to post specific issues I see here.

**Comment by nbuuck** [comment]
![screenshot_20170806-112844](https://user-images.githubusercontent.com/3183127/29004731-8e49593a-7a9a-11e7-98f3-fda9b75b1d87.png)

Example of the most recent handler diary entry body being truncated in the RSS feed in the Feedly reader. Additionally, the RSS item just links to the diary index page rather than the specific entry.

**Comment by jrmain** [comment]
Problems with the full feed remain: non-breaking spaces, quotes, angle brackets, URLs, and PRE tags are all causing problems. The result is a lot of garbage text and missing content in the feed.

The content itself doesn't seem to be a problem; I pasted the page source for several problematic posts into a Wordpress blog and the resulting posts and corresponding feed look fine.

I've attached a screenshot that shows some of the issues.

![sansdiary22688_2017aug07](https://user-images.githubusercontent.com/1110694/29028630-c7a1bcd2-7b39-11e7-8578-aaf73382ec5c.png)

**Comment by jrmain** [comment]
Today's Patch Tuesday post is seriously messed up.
![sansdiary22694_2017aug08](https://user-images.githubusercontent.com/1110694/29089295-a77569f2-7c30-11e7-9c19-a48fe16e66ae.png)

**Comment by jrmain** [comment]
At first glance, today's post titled 'Outlook Web Access based attacks' looks okay. But that's because the post doesn't include any images, blockquotes, or links. And in fact there are still problems, they are just harder to spot: all apostrophes and quotes are missing.

Note that the 'title only' feed, which now contains the first paragraph of each post, shows the same problem.

![image](https://user-images.githubusercontent.com/1110694/29241058-a25a1c12-7f26-11e7-8021-bed021c782fa.png)

**Comment by jrmain** [comment]
The feed item for today's post by Renato Marinho ([EngineBox Malware Supports 10+ Brazilian Banks](https://isc.sans.edu/forums/diary/EngineBox+Malware+Supports+10+Brazilian+Banks/22736/)) looks perfect, in the sense that there are no issues other than those that are visible on the source page.

So either you've fixed the problem, or this particular author has found a way to use your post editor that doesn't cause all the problems outlined above.

**Comment by jullrich** [comment]
I made misc. changes last week to improve the feed. not sure if this fixed "all" issues, but it should have fixed the issues pointed out above.

**Comment by jrmain** [comment]
I'll continue to monitor both feeds and report any further issues. One thing: references to the 'title only' feed should really be changed, since that feed now shows the first paragraph.

**Comment by jrmain** [comment]
So far so good. Looks like whatever setting(s) you changed did the trick. No major structural changes were required, I assume?

**Comment by jullrich** [comment]
multiple small changes for the most part.

**Comment by jrmain** [comment]
I haven't seen any more problems since the last set of changes. Thanks for fixing this!
