### ISSUE TITLE
dshield.org/my404.html returns a blank page

### ISSUE THREAD

**Issue by da2x** [jullrich/ISC-Bugs#24]
HTTP status 200 with lots of custom headers, but the page is empty (0 bytes besides the headers).

**Comment by jullrich** [comment]
this is fixed now. note that you have to click "submit".

**Comment by da2x** [comment]
The page still doesn’t load for me. It’s entirely blank with no content beside the HTTP headers.

**Comment by jullrich** [comment]
please email me your userid or email address so I can impersonate you and see if there is anything causing this for you ( jullrich at sans.edu)

**Comment by jullrich** [comment]
I found one possible issue that would affect users who have not yet submitted any 404 reports.

**Comment by da2x** [comment]
That could potentially be my issue. I wanted to see if I’ve set it up properly and whether submissions worked or not. It could be that I haven’t yet submitted anything.

**Comment by da2x** [comment]
It works now!

**Comment by jullrich** [comment]
good. closing it now. Let me know if you need help getting reports submitted.
